/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.telas;

import br.com.config.ConnectionFactory;
import br.com.model.OrdemServico;
import br.com.utilidades.ConfigTelas;

/**
 *
 * @author Producao
 */
public class TelaInserirServicoNaOS extends javax.swing.JFrame {

    private OrdemServico ordemServico;
    
    /**
     * Creates new form TelaInserirServicoNaOS
     * @param os
     */
    public TelaInserirServicoNaOS(OrdemServico os) {
        initComponents();
        
        this.ordemServico = os;
        
        this.jTextFieldNome.setText(this.ordemServico.getIdcliente().getNome());
        this.jTextFieldEquipamento.setText(this.ordemServico.getIdequipamento().getDescricao());
        this.jLabelNrOs.setText(this.ordemServico.getIdordemServico().toString());
        ConfigTelas ct = new ConfigTelas(this);
        ct.carregarConfig(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = ConnectionFactory.getEntityManager();
        servicoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Servico s");
        servicoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : servicoQuery.getResultList();
        servicoListCellRenderer1 = new br.com.renderizadores.ServicoListCellRenderer();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListServicosSelecionados = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListServicos = new javax.swing.JList();
        jButtonAdicionaServico = new javax.swing.JButton();
        jButtonRemoveServico = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelNrOs = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEquipamento = new javax.swing.JTextField();

        servicoListCellRenderer1.setText("servicoListCellRenderer1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListServicosSelecionados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListServicosSelecionados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 160, 270));

        jListServicos.setCellRenderer(servicoListCellRenderer1);

        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, servicoList, jListServicos);
        bindingGroup.addBinding(jListBinding);

        jScrollPane2.setViewportView(jListServicos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 270));

        jButtonAdicionaServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/right_32.png"))); // NOI18N
        jButtonAdicionaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionaServicoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdicionaServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jButtonRemoveServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/left_32.png"))); // NOI18N
        jButtonRemoveServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveServicoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRemoveServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitulo.setText("Inserir Serviços na OS nr:");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jTextFieldNome.setEditable(false);
        jPanel1.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabelNrOs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNrOs.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNrOs.setText("jLabel18");
        jPanel1.add(jLabelNrOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel2.setText("Equipamento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jTextFieldEquipamento.setEditable(false);
        jPanel1.add(jTextFieldEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionaServicoActionPerformed

        

    }//GEN-LAST:event_jButtonAdicionaServicoActionPerformed

    private void jButtonRemoveServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveServicoActionPerformed
        
        
        
    }//GEN-LAST:event_jButtonRemoveServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInserirServicoNaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInserirServicoNaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInserirServicoNaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInserirServicoNaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaInserirServicoNaOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButtonAdicionaServico;
    private javax.swing.JButton jButtonRemoveServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNrOs;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList jListServicos;
    private javax.swing.JList jListServicosSelecionados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldEquipamento;
    private javax.swing.JTextField jTextFieldNome;
    private java.util.List<br.com.model.Servico> servicoList;
    private br.com.renderizadores.ServicoListCellRenderer servicoListCellRenderer1;
    private javax.persistence.Query servicoQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
